### ISSUE TITLE
A fresh install on AWS (EKS) is unable to connect to github

### ISSUE THREAD

**Issue by pdodds** [jenkins-x/jenkins-x-platform#4768]
I did a fresh install and then imported a project from GitHub.

The branch indexing failed in Jenkins,  looking at the branch log you see

Invalid scan credentials when using anonymous access to connect

When digging into the Jenkins log I found 

```
SEVERE: Failed KubernetesCredentialProvider.startWatchingForSecrets
java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1083)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: java.lang.NullPointerException
	at com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.SecretUtils.getKeyName(SecretUtils.java:203)
	at com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.SecretUtils.getNonNullSecretData(SecretUtils.java:168)
	at com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.convertors.StringCredentialConvertor.convert(StringCredentialConvertor.java:51)
	at com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.convertors.StringCredentialConvertor.convert(StringCredentialConvertor.java:38)
	at com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.KubernetesCredentialProvider.convertSecret(KubernetesCredentialProvider.java:194)
	at com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.KubernetesCredentialProvider.startWatchingForSecrets(KubernetesCredentialProvider.java:90)
	... 13 more
```

This appears to be related to https://issues.jenkins-ci.org/browse/JENKINS-54313 and the workaround listed, which is to add annotations to all secrets worked (after deleting the jenkins pod)

**Comment by rawlingsj** [comment]
Yes this is related and there's already a proposed fix for the plugin https://github.com/jenkinsci/kubernetes-credentials-provider-plugin/pull/20 

/kind bug
/area install
/priority important-soon
/assign jnord

**Comment by rawlingsj** [comment]
@jtnord this one might interest you.
